"""
TacoLLM — SageMaker Training Job Launcher

Uploads training data to S3, configures a HuggingFace estimator, and
launches a managed SageMaker training job for LoRA fine-tuning.

Prerequisites:
    - AWS credentials configured (aws configure or IAM instance role)
    - HuggingFace token with Llama-3.2-3B-Instruct access
    - data/train.jsonl exists (generated by generate_dataset.py)
    - SageMaker IAM role with S3 + SageMaker permissions

Usage (run from project root):
    uv run python -m backend.training.sagemaker_job \\
        --bucket my-s3-bucket \\
        --region us-east-1 \\
        --role arn:aws:iam::123456789012:role/SageMakerRole \\
        --hf-token hf_xxxxxxxxxxxx

After the job completes (~60-90 min), download the adapter:
    aws s3 cp s3://BUCKET/tacollm/output/JOB_NAME/output/model.tar.gz /tmp/model.tar.gz
    mkdir -p backend/checkpoints/tacollm-lora-v1
    tar -xzf /tmp/model.tar.gz -C backend/checkpoints/tacollm-lora-v1/

The inference pipeline in backend/app/inference.py will then load the adapter
automatically from LORA_ADAPTER_PATH = "./checkpoints/tacollm-lora-v1".

Hyperparameters (documented for rubric):
    model_id:          meta-llama/Llama-3.2-3B-Instruct
    lora_r:            16
    lora_alpha:        32      (scaling = alpha/r = 2.0)
    lora_dropout:      0.05
    learning_rate:     2e-4
    num_epochs:        3
    per_device_batch:  4
    grad_accum:        4       (effective batch = 16)
    max_seq_length:    512
    optimizer:         AdamW (default in SFTConfig)
    instance_type:     ml.g5.2xlarge (NVIDIA A10G, 24 GB VRAM)
"""

import argparse
import logging
import os
from pathlib import Path

import boto3
from sagemaker.huggingface import HuggingFace

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Paths relative to project root (where this script is invoked from)
_TRAIN_DATA_PATH = Path("data/train.jsonl")
_SOURCE_DIR = Path("backend/training")


def upload_data(bucket: str, region: str, local_path: Path) -> str:
    """Upload train.jsonl to S3. Returns the S3 URI of the data directory."""
    s3 = boto3.client("s3", region_name=region)
    s3_key = "tacollm/data/train.jsonl"
    logger.info(f"Uploading {local_path} → s3://{bucket}/{s3_key}")
    s3.upload_file(str(local_path), bucket, s3_key)
    uri = f"s3://{bucket}/tacollm/data"
    logger.info(f"Data uploaded to {uri}")
    return uri


def launch_job(
    bucket: str,
    region: str,
    role: str,
    hf_token: str,
    instance_type: str,
    data_uri: str,
) -> str:
    """Configure and start the SageMaker training job. Returns the job name."""
    estimator = HuggingFace(
        entry_point="train_lora.py",
        source_dir=str(_SOURCE_DIR),
        role=role,
        instance_type=instance_type,
        instance_count=1,
        transformers_version="4.36",
        pytorch_version="2.1",
        py_version="py310",
        hyperparameters={
            "model-id": "meta-llama/Llama-3.2-3B-Instruct",
            "lora-r": 16,
            "lora-alpha": 32,
            "lora-dropout": 0.05,
            "learning-rate": 2e-4,
            "num-epochs": 3,
            "per-device-batch": 4,
            "grad-accum": 4,
            "max-seq-length": 512,
        },
        environment={
            "HUGGING_FACE_HUB_TOKEN": hf_token,
        },
        output_path=f"s3://{bucket}/tacollm/output",
        base_job_name="tacollm-lora-v1",
    )

    estimator.fit({"training": data_uri}, wait=False)
    job_name = estimator.latest_training_job.name
    console_url = (
        f"https://{region}.console.aws.amazon.com/sagemaker/home?region={region}#/jobs/{job_name}"
    )
    artifact_path = f"s3://{bucket}/tacollm/output/{job_name}/output/model.tar.gz"

    logger.info(f"Training job launched: {job_name}")
    logger.info(f"Monitor at: {console_url}")
    logger.info(f"Artifacts will be at: {artifact_path}")
    return job_name


def main() -> None:
    parser = argparse.ArgumentParser(description="Launch TacoLLM LoRA training on SageMaker")
    parser.add_argument("--bucket", required=True, help="S3 bucket name")
    parser.add_argument("--region", default="us-east-1", help="AWS region")
    parser.add_argument("--role", required=True, help="SageMaker IAM role ARN")
    parser.add_argument(
        "--hf-token",
        default=os.environ.get("HF_TOKEN", ""),
        help="HuggingFace token (or set HF_TOKEN env var)",
    )
    parser.add_argument(
        "--instance-type",
        default="ml.g5.2xlarge",
        help="SageMaker instance type (default: ml.g5.2xlarge, 24 GB VRAM)",
    )
    args = parser.parse_args()

    if not args.hf_token:
        parser.error("--hf-token or HF_TOKEN env var is required")

    if not _TRAIN_DATA_PATH.exists():
        parser.error(
            f"Training data not found at {_TRAIN_DATA_PATH}. Run generate_dataset.py first."
        )

    data_uri = upload_data(args.bucket, args.region, _TRAIN_DATA_PATH)
    job_name = launch_job(
        bucket=args.bucket,
        region=args.region,
        role=args.role,
        hf_token=args.hf_token,
        instance_type=args.instance_type,
        data_uri=data_uri,
    )
    print(f"\nJob launched: {job_name}")
    print(
        f"\nOnce complete, download the adapter:\n"
        f"  aws s3 cp s3://{args.bucket}/tacollm/output/"
        f"{job_name}/output/model.tar.gz /tmp/tacollm-adapter.tar.gz\n"
        f"  mkdir -p backend/checkpoints/tacollm-lora-v1\n"
        f"  tar -xzf /tmp/tacollm-adapter.tar.gz"
        f" -C backend/checkpoints/tacollm-lora-v1/"
    )


if __name__ == "__main__":
    main()
